AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DomainName:
    Type: String
  Verification:
    Type: String
  Ttl:
    Type: String
  DmarcAction:
    Type: String
  DmarcEmail:
    Type: String
  Dkim:
    Type: String

Resources:
  ProtonMailRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: "All records for protonmail email forwarding"
      HostedZoneName: !Sub ${DomainName}.
      RecordSets:
        - Type: TXT
          TTL: !Ref Ttl
          Name: !Sub ${DomainName}.
          ResourceRecords:
          - !Sub '"protonmail-verification=${Verification}"'
          - '"v=spf1 include:_spf.protonmail.ch mx ~all"'
        - Type: TXT
          TTL: !Ref Ttl
          Name: !Sub _dmarc.${DomainName}.
          ResourceRecords:
          - !Sub '"v=DMARC1; p=${DmarcAction}; fo=1; ruf=mailto:${DmarcEmail}"'
        - Type: MX
          TTL: !Ref Ttl
          Name: !Sub ${DomainName}.
          ResourceRecords:
          - '10 mail.protonmail.ch.'
          - '20 mailsec.protonmail.ch.'
        - Type: CNAME
          TTL: !Ref Ttl
          Name: !Sub protonmail._domainkey.${DomainName}.
          ResourceRecords:
          - !Sub protonmail.domainkey.${Dkim}.domains.proton.ch.
        - Type: CNAME
          TTL: !Ref Ttl
          Name: !Sub protonmail2._domainkey.${DomainName}.
          ResourceRecords:
          - !Sub protonmail2.domainkey.${Dkim}.domains.proton.ch.
        - Type: CNAME
          TTL: !Ref Ttl
          Name: !Sub protonmail3._domainkey.${DomainName}.
          ResourceRecords:
          - !Sub protonmail3.domainkey.${Dkim}.domains.proton.ch.
