AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DomainName:
    Type: String
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id

Resources:
  HttpsCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - !Sub www.${DomainName}
      DomainValidationOptions:
        - DomainName: !Sub ${DomainName}
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub www.${DomainName}
          HostedZoneId: !Ref HostedZoneId

Outputs:
  CertArn:
    Description: https cert for (www.)frogamic.website
    Value: !Ref HttpsCert
