AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Stage:
    Type: String
  Project:
    Type: String
  DomainName:
    Type: String
  DomainName2:
    Type: String
  CertArn:
    Type: AWS::SSM::Parameter::Value<String>
  ContentBucket:
    Type: AWS::SSM::Parameter::Value<String>
  LogsBucket:
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  ResponseHeaders:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub ${Project}ResponseHeaders
        RemoveHeadersConfig:
          Items:
            - Header: Server
        SecurityHeadersConfig:
          ContentSecurityPolicy:
            ContentSecurityPolicy: !Join
              - "; "
              - - default-src 'none'
                - img-src 'self'
                - script-src 'self'
                - style-src 'unsafe-inline' 'self'
                - object-src 'none'
                - frame-src 'self'
            Override: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: same-origin
            Override: true
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 63072000
            IncludeSubdomains: false
            Preload: false
            Override: true
          XSSProtection:
            ModeBlock: true
            Protection: true
            Override: true

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !Sub ${ContentBucket}.s3.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${ContentAccessId}
        HttpVersion: http2
        Enabled: true
        Comment: !Sub ${AWS::StackName}Distribution
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: false
          Bucket: !Sub ${LogsBucket}.s3.amazonaws.com
          Prefix: !Ref AWS::StackName
        Aliases:
          - !Ref DomainName
          - !Sub www.${DomainName}
          - !Ref DomainName2
          - !Sub www.${DomainName2}
        DefaultCacheBehavior:
          DefaultTTL: 3600
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          ResponseHeadersPolicyId: !Ref ResponseHeaders
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref CertArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018

  ContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentBucket
      PolicyDocument:
        Statement:
          - Action: s3:Get*
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${ContentBucket}/*
            Principal:
              CanonicalUser: !GetAtt ContentAccessId.S3CanonicalUserId

  ContentAccessId:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${AWS::StackName}AccessId

  DotWebsiteDnsRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub ${DomainName}.
      RecordSets:
        - Type: A
          Name: !Sub ${DomainName}.
          AliasTarget:
            DNSName: !GetAtt Distribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
        - Type: A
          Name: !Sub www.${DomainName}.
          AliasTarget:
            DNSName: !GetAtt Distribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2

  DotComDnsRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub ${DomainName2}.
      RecordSets:
        - Type: A
          Name: !Sub ${DomainName2}.
          AliasTarget:
            DNSName: !GetAtt Distribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
        - Type: A
          Name: !Sub www.${DomainName2}.
          AliasTarget:
            DNSName: !GetAtt Distribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
